language: node_js
notifications:
  email:
    on_success: never
    on_failure: change
node_js:
  - "node"
  - "8"
#deploy:
#  provider: heroku
#  api_key:
#    secure: ""
#  app: cwp34-article
#  on:
#    repo: SazanYa/cwp34
before_script:
  - npm install